export const SKU_DROPDOWN_OPTIONS: Record<string, string[]> = {
  gender: [
    "Mens",
    "Womens",
    "Unisex",
    "Boys",
    "Girls",
    "Kids",
    "Youth",
  ],
  watch_type: [
    "Diving/Dive",
    "Dress",
    "Chronograph",
    "Sports",
    "Field",
    "Pilot/Aviator",
    "GMT",
    "Analog",
    "Digital",
    "Smartwatch",
    "Mechanical",
    "Chronometer",
    "Skeleton",
    "Tourbillon",
    "Moonphase",
    "Perpetual Calendar",
    "Military",
  ],
  case_material: [
    "Stainless Steel 316L",
    "Stainless Steel 904L",
    "Titanium Grade 2",
    "Titanium Grade 5",
    "Ceramic (Zirconium Oxide)",
    "Ceramic (Aluminium Oxide)",
    "Gold 18K",
    "Gold 14K",
    "Platinum",
    "Aluminum",
    "PVD-coated",
    "Carbon Fiber",
    "Bronze",
    "Tantalum",
    "Porcelain",
    "Wood",
    "Resin",
  ],
  movement_type: [
    "Quartz",
    "Mechanical (Manual Wind)",
    "Automatic (Self-Winding)",
    "Spring Drive",
    "Kinetic (Eco-Drive)",
    "Solar",
    "Eco-Drive",
    "Radio-Controlled",
    "GPS Time",
    "Tourbillon",
    "Co-Axial",
  ],
  display_type: [
    "Analog",
    "Digital LCD",
    "Digital LED",
    "Digital OLED",
    "E-Ink",
    "Hybrid",
  ],
  water_resistance: [
    "3 ATM (30m)",
    "5 ATM (50m)",
    "10 ATM (100m)",
    "20 ATM (200m)",
    "30 ATM (300m)",
    "50 ATM (500m)",
    "100 ATM (1000m)",
    "Splash Resistant",
  ],
  dial_color: [
    "Black",
    "White/Silver",
    "Blue",
    "Green",
    "Grey",
    "Champagne",
    "Brown",
    "Red",
    "Orange",
    "Purple",
    "Mother-of-Pearl",
    "Gold",
    "Pink",
    "Yellow",
    "Teal",
    "Navy",
    "Burgundy",
    "Skeleton/Transparent",
  ],
};

export const SKU_DROPDOWN_ARABIC_TRANSLATIONS: Record<string, Record<string, string>> = {
  gender: {
    Mens: "رجالي",
    Womens: "نسائي",
    Unisex: "للجنسين",
    Boys: "أولاد",
    Girls: "بنات",
    Kids: "أطفال",
    Youth: "شباب",
  },
  watch_type: {
    "Diving/Dive": "غوص / غواص",
    Dress: "رسمي",
    Chronograph: "كرونوغراف",
    Sports: "رياضي",
    Field: "ميداني",
    "Pilot/Aviator": "طيران",
    GMT: "توقيت جرينتش (GMT)",
    Analog: "عقارب",
    Digital: "رقمي",
    Smartwatch: "ساعة ذكية",
    Mechanical: "ميكانيكي",
    Chronometer: "كرونومتر",
    Skeleton: "سكليتون",
    Tourbillon: "توربيون",
    Moonphase: "مراحل القمر",
    "Perpetual Calendar": "تقويم دائم",
    Military: "عسكري",
  },
  case_material: {
    "Stainless Steel 316L": "ستانلس ستيل 316L",
    "Stainless Steel 904L": "ستانلس ستيل 904L",
    "Titanium Grade 2": "تيتانيوم درجة 2",
    "Titanium Grade 5": "تيتانيوم درجة 5",
    "Ceramic (Zirconium Oxide)": "سيراميك (أكسيد الزركونيوم)",
    "Ceramic (Aluminium Oxide)": "سيراميك (أكسيد الألمنيوم)",
    "Gold 18K": "ذهب عيار 18",
    "Gold 14K": "ذهب عيار 14",
    Platinum: "بلاتين",
    Aluminum: "ألمنيوم",
    "PVD-coated": "مطلي بـ PVD",
    "Carbon Fiber": "ألياف كربون",
    Bronze: "برونز",
    Tantalum: "تانتالوم",
    Porcelain: "بورسلين",
    Wood: "خشب",
    Resin: "راتنج",
  },
  movement_type: {
    Quartz: "كوارتز",
    "Mechanical (Manual Wind)": "ميكانيكي (تعبئة يدوية)",
    "Automatic (Self-Winding)": "أوتوماتيكي (ذاتي التعبئة)",
    "Spring Drive": "سبرينج درايف",
    "Kinetic (Eco-Drive)": "كينتيك",
    Solar: "شمسي",
    "Eco-Drive": "إيكو درايف",
    "Radio-Controlled": "تحكم بالراديو",
    "GPS Time": "توقيت GPS",
    Tourbillon: "توربيون",
    "Co-Axial": "كو أكسيال",
  },
  display_type: {
    Analog: "عقارب",
    "Digital LCD": "رقمي LCD",
    "Digital LED": "رقمي LED",
    "Digital OLED": "رقمي OLED",
    "E-Ink": "حبر إلكتروني",
    Hybrid: "هجين",
  },
  water_resistance: {
    "3 ATM (30m)": "3 ATM (30م)",
    "5 ATM (50m)": "5 ATM (50م)",
    "10 ATM (100m)": "10 ATM (100م)",
    "20 ATM (200m)": "20 ATM (200م)",
    "30 ATM (300m)": "30 ATM (300م)",
    "50 ATM (500m)": "50 ATM (500م)",
    "100 ATM (1000m)": "100 ATM (1000م)",
    "Splash Resistant": "مقاوم للرذاذ",
  },
  dial_color: {
    Black: "أسود",
    "White/Silver": "أبيض / فضي",
    Blue: "أزرق",
    Green: "أخضر",
    Grey: "رمادي",
    Champagne: "شامبانيا",
    Brown: "بني",
    Red: "أحمر",
    Orange: "برتقالي",
    Purple: "بنفسجي",
    "Mother-of-Pearl": "عرق اللؤلؤ",
    Gold: "ذهبي",
    Pink: "وردي",
    Yellow: "أصفر",
    Teal: "أزرق مخضر",
    Navy: "كحلي",
    Burgundy: "عنابي",
    "Skeleton/Transparent": "سكليتون / شفاف",
  },
};

export const DEFAULT_WATCH_FIELDS = [
  { key: "gender", label: "Gender", value_en: "Mens", value_ar: "رجالي" },
  { key: "watch_type", label: "Watch Type", value_en: "Chronograph", value_ar: "كرونوغراف" },
  { key: "case_material", label: "Case Material", value_en: "Stainless Steel 316L", value_ar: "ستانلس ستيل 316L" },
  { key: "movement_type", label: "Movement Type", value_en: "Automatic (Self-Winding)", value_ar: "أوتوماتيكي (ذاتي التعبئة)" },
  { key: "display_type", label: "Display Type", value_en: "Analog", value_ar: "عقارب" },
  { key: "water_resistance", label: "Water Resistance", value_en: "20 ATM (200m)", value_ar: "20 ATM (200م)" },
  { key: "dial_color", label: "Dial Color", value_en: "Black", value_ar: "أسود" },
];
