/**
 * FINAL dropdowns (canonical keys -> Arabic label)
 * IMPORTANT: English values are normalized lowercase keys.
 */
export const WATCH_DROPDOWN_TRANSLATIONS_AR = {
  gender: {
    mens: "رجالي",
    womens: "نسائي",
    unisex: "للجنسين",
    boys: "أولاد",
    girls: "بنات",
  },
  watch_type: {
    diving: "غوص/غواص",
    dive: "غوص/غواص",
    dress: "رسمي",
    chronograph: "كرونوغراف",
    sports: "رياضي",
    gmt: "توقيت جرينتش (GMT)",
    analog: "عقارب",
    digital: "رقمي",
    mechanical: "ميكانيكي",
    skeleton: "سكليتون",
  },
  case_material: {
    "stainless steel 316l": "ستانلس ستيل 316L",
    "stainless steel": "ستانلس ستيل",
    "titanium grade 2": "تيتانيوم درجة 2",
    titanium: "تيتانيوم",
    "ceramic (zirconium oxide)": "سيراميك (أكسيد الزركونيوم)",
    ceramic: "سيراميك",
    platinum: "بلاتين",
    aluminum: "ألمنيوم",
    "pvd-coated": "مطلي بـ PVD",
    "carbon fiber": "ألياف كربون",
    resin: "راتنج",
    plastic: "بلاستيك",
    metal: "معدن",
  },
  movement_type: {
    quartz: "كوارتز",
    "automatic (self-winding)": "أوتوماتيكي (ذاتي التعبئة)",
    "self-winding": "أوتوماتيكي (ذاتي التعبئة)",
    solar: "شمسي",
  },
  display_type: {
    analog: "عقارب",
    "digital lcd": "رقمي LCD",
    lcd: "رقمي LCD",
    hybrid: "هجين",
  },
  water_resistance: {
    "3 atm": "3 ATM (30م)",
    "5 atm": "5 ATM (50م)",
    "10 atm": "10 ATM (100م)",
    "20 atm": "20 ATM (200م)",
    "splash resistant": "مقاوم للرذاذ",
  },
  dial_color: {
    black: "أسود",
    "white/silver": "أبيض/فضي",
    silver: "فضي",
    blue: "أزرق",
    green: "أخضر",
    grey: "رمادي",
    champagne: "شامبانيا",
    brown: "بني",
    red: "أحمر",
    purple: "بنفسجي",
    "mother-of-pearl": "عرق اللؤلؤ",
    gold: "ذهبي",
    pink: "وردي",
    yellow: "أصفر",
    teal: "أزرق مخضر",
    navy: "كحلي",
    burgundy: "عنابي",
    "skeleton/transparent": "سكليتون/شفاف",
    beige: "بيج",
    "multi-color": "متعدد الألوان",
    khaki: "كاكي",
  },
  band_material: {
    leather: "جلد",
    calfskin: "جلد عجل",
    "synthetic leather": "جلد صناعي",
    "genuine leather": "جلد طبيعي",
    "stainless steel": "ستانلس ستيل",
    ceramic: "سيراميك",
    rubber: "مطاط",
    "fkm rubber": "مطاط FKM",
    silicone: "سيليكون",
    "textile/nylon": "نسيج/نايلون",
    polyurethane: "بولي يوريثان",
    nylon: "نايلون",
    satin: "ساتان",
    pvd: "طلاء PVD",
    "nato strap": "سوار ناتو",
    metal: "معدن",
    resin: "راتنج",
    tpu: "بولي يوريثان حراري (TPU)",
  },
} as const;

export const WATCH_DROPDOWN_FIELDS = {
  gender: ["mens", "womens", "unisex", "boys", "girls"],
  watch_type: [
    "diving",
    "dive",
    "dress",
    "chronograph",
    "sports",
    "gmt",
    "analog",
    "digital",
    "mechanical",
    "skeleton",
  ],
  case_material: [
    "stainless steel 316l",
    "stainless steel",
    "titanium grade 2",
    "titanium",
    "ceramic (zirconium oxide)",
    "ceramic",
    "platinum",
    "aluminum",
    "pvd-coated",
    "carbon fiber",
    "resin",
    "plastic",
    "metal",
  ],
  movement_type: ["quartz", "automatic (self-winding)", "self-winding", "solar"],
  display_type: ["analog", "digital lcd", "lcd", "hybrid"],
  water_resistance: ["3 atm", "5 atm", "10 atm", "20 atm", "splash resistant"],
  dial_color: [
    "black",
    "white/silver",
    "silver",
    "blue",
    "green",
    "grey",
    "champagne",
    "brown",
    "red",
    "purple",
    "mother-of-pearl",
    "gold",
    "pink",
    "yellow",
    "teal",
    "navy",
    "burgundy",
    "skeleton/transparent",
    "beige",
    "multi-color",
    "khaki",
  ],
  band_material: [
    "leather",
    "calfskin",
    "synthetic leather",
    "genuine leather",
    "stainless steel",
    "ceramic",
    "rubber",
    "fkm rubber",
    "silicone",
    "textile/nylon",
    "polyurethane",
    "nylon",
    "satin",
    "pvd",
    "nato strap",
    "metal",
    "resin",
    "tpu",
  ],
} as const;

export type WatchDropdownFieldName = keyof typeof WATCH_DROPDOWN_FIELDS;

export const WATCH_DIRECT_FIELDS = [
  "model_number",
  "case_diameter",
  "case_thickness",
  "description",
] as const;

export type WatchDirectFieldName = (typeof WATCH_DIRECT_FIELDS)[number];

